import Img from '../../assets/images/Schatow-img.jpg';
const customersAll = [
  {
    id: 0,
    img: Img,
    name: 'Alex Shatov',
    email: 'alexshatov@gmail.com',
    spend: 2890.66,
  },
  {
    id: 1,
    img: Img,
    name: 'Alex Shatov1',
    email: 'alexshatov@gmail.com',
    spend: 2890.66,
  },
  {
    id: 2,
    img: Img,
    name: 'Alex Shatov2',
    email: 'alexshatov@gmail.com',
    spend: 2890.66,
  },
  {
    id: 3,
    img: Img,
    name: 'Alex Shatov3',
    email: 'alexshatov@gmail.com',
    spend: 2890.66,
  },
  {
    id: 4,
    img: Img,
    name: 'Alex Shatov4',
    email: 'alexshatov@gmail.com',
    spend: 2890.66,
  },
  {
    id: 5,
    img: Img,
    name: 'Alex Shatov5',
    email: 'alexshatov@gmail.com',
    spend: 2890.66,
  },
  {
    id: 6,
    img: Img,
    name: 'Alex Shatov6',
    email: 'alexshatov@gmail.com',
    spend: 2890.66,
  },
  {
    id: 7,
    img: Img,
    name: 'Alex Shatov7',
    email: 'alexshatov@gmail.com',
    spend: 2890.66,
  },
  {
    id: 8,
    img: Img,
    name: 'Alex Shatov8',
    email: 'alexshatov@gmail.com',
    spend: 2890.66,
  },
  {
    id: 9,
    img: Img,
    name: 'Alex Shatov9',
    email: 'alexshatov@gmail.com',
    spend: 2890.66,
  },
  {
    id: 10,
    img: Img,
    name: 'Alex Shatov10',
    email: 'alexshatov@gmail.com',
    spend: 2890.66,
  },
  {
    id: 11,
    img: Img,
    name: 'Alex Shatov11',
    email: 'alexshatov@gmail.com',
    spend: 2890.66,
  },
  {
    id: 12,
    img: Img,
    name: 'Alex Shatov12',
    email: 'alexshatov@gmail.com',
    spend: 2890.66,
  },
];

export const customersRev = customersAll.reverse();
